# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'messageBox_confirmation.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(321, 177)
        Dialog.setStyleSheet("*{\n"
"background-color:transparent;\n"
"background:transparent;\n"
"    border:none;\n"
"padding:0;\n"
"margin:0;\n"
"color:#fff;\n"
"}\n"
"\n"
"#widget{\n"
"background-color:rgba(20,20,20,250);\n"
"border-radius:20px;\n"
"border-top-right-radius:0px;\n"
"}\n"
"\n"
"#closeMessageBtn:hover{\n"
"background-color:rgb(104, 102, 122);\n"
"border-radius:10px;\n"
"}\n"
"\n"
"#noBtn:hover{\n"
"background-color:rgb(104, 102, 122);\n"
"border-bottom-right-radius:20px;\n"
"}\n"
"\n"
"#yesBtn:hover{\n"
"background-color:rgb(104, 102, 122);\n"
"}\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.widget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.closeMessageBtn = QtWidgets.QPushButton(self.frame)
        self.closeMessageBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icons/x-circle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeMessageBtn.setIcon(icon)
        self.closeMessageBtn.setIconSize(QtCore.QSize(24, 24))
        self.closeMessageBtn.setObjectName("closeMessageBtn")
        self.horizontalLayout.addWidget(self.closeMessageBtn, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_2.addWidget(self.frame, 0, QtCore.Qt.AlignTop)
        self.frame_2 = QtWidgets.QFrame(self.widget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setMinimumSize(QtCore.QSize(40, 40))
        self.label.setMaximumSize(QtCore.QSize(40, 40))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../icons/alert_triangle_white.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.messageLbl = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.messageLbl.sizePolicy().hasHeightForWidth())
        self.messageLbl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.messageLbl.setFont(font)
        self.messageLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.messageLbl.setObjectName("messageLbl")
        self.horizontalLayout_3.addWidget(self.messageLbl)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.widget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.yesBtn = QtWidgets.QPushButton(self.frame_3)
        self.yesBtn.setMinimumSize(QtCore.QSize(60, 35))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.yesBtn.setFont(font)
        self.yesBtn.setObjectName("yesBtn")
        self.yesBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.horizontalLayout_2.addWidget(self.yesBtn)
        self.noBtn = QtWidgets.QPushButton(self.frame_3)
        self.noBtn.setMinimumSize(QtCore.QSize(60, 35))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.noBtn.setFont(font)
        self.noBtn.setObjectName("noBtn")
        self.noBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.horizontalLayout_2.addWidget(self.noBtn)
        self.verticalLayout_2.addWidget(self.frame_3, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignBottom)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.messageLbl.setText(_translate("Dialog", "message"))
        self.yesBtn.setText(_translate("Dialog", "yes"))
        self.noBtn.setText(_translate("Dialog", "No"))
