# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'terms_and_conditions.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Terms_and_conditions(object):
    def setupUi(self, Terms_and_conditions):
        Terms_and_conditions.setObjectName("Terms_and_conditions")
        Terms_and_conditions.resize(599, 437)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/Nerfliz_logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Terms_and_conditions.setWindowIcon(icon)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Terms_and_conditions)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frm_image = QtWidgets.QFrame(Terms_and_conditions)
        self.frm_image.setMaximumSize(QtCore.QSize(180, 16777215))
        self.frm_image.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_image.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_image.setObjectName("frm_image")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frm_image)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_image = QtWidgets.QLabel(self.frm_image)
        self.lbl_image.setMaximumSize(QtCore.QSize(170, 70))
        self.lbl_image.setText("")
        self.lbl_image.setPixmap(QtGui.QPixmap("images/logo_nerfliz_tipo.png"))
        self.lbl_image.setScaledContents(True)
        self.lbl_image.setObjectName("lbl_image")
        self.verticalLayout.addWidget(self.lbl_image, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout.addWidget(self.frm_image)
        self.frm_principal = QtWidgets.QFrame(Terms_and_conditions)
        self.frm_principal.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_principal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_principal.setObjectName("frm_principal")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frm_principal)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frm_termsandconditions_text = QtWidgets.QFrame(self.frm_principal)
        self.frm_termsandconditions_text.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_termsandconditions_text.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_termsandconditions_text.setObjectName("frm_termsandconditions_text")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frm_termsandconditions_text)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lbl_terms_and_conditions = QtWidgets.QLabel(self.frm_termsandconditions_text)
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        self.lbl_terms_and_conditions.setFont(font)
        self.lbl_terms_and_conditions.setObjectName("lbl_terms_and_conditions")
        self.horizontalLayout_6.addWidget(self.lbl_terms_and_conditions, 0, QtCore.Qt.AlignLeft)
        self.btn_close_terms_conditions = QtWidgets.QPushButton(self.frm_termsandconditions_text)
        self.btn_close_terms_conditions.setMinimumSize(QtCore.QSize(24, 24))
        self.btn_close_terms_conditions.setMaximumSize(QtCore.QSize(24, 24))
        self.btn_close_terms_conditions.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_close_terms_conditions.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/x.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_close_terms_conditions.setIcon(icon1)
        self.btn_close_terms_conditions.setIconSize(QtCore.QSize(24, 24))
        self.btn_close_terms_conditions.setObjectName("btn_close_terms_conditions")
        self.horizontalLayout_6.addWidget(self.btn_close_terms_conditions, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_2.addWidget(self.frm_termsandconditions_text)
        self.frm_terms_and_conditions = QtWidgets.QFrame(self.frm_principal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frm_terms_and_conditions.sizePolicy().hasHeightForWidth())
        self.frm_terms_and_conditions.setSizePolicy(sizePolicy)
        self.frm_terms_and_conditions.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_terms_and_conditions.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_terms_and_conditions.setObjectName("frm_terms_and_conditions")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frm_terms_and_conditions)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.txt_terms_and_conditions = QtWidgets.QPlainTextEdit(self.frm_terms_and_conditions)
        self.txt_terms_and_conditions.setReadOnly(True)
        self.txt_terms_and_conditions.setObjectName("txt_terms_and_conditions")
        self.verticalLayout_3.addWidget(self.txt_terms_and_conditions)
        self.lay_hor_buttons = QtWidgets.QHBoxLayout()
        self.lay_hor_buttons.setObjectName("lay_hor_buttons")
        self.btn_agree = QtWidgets.QPushButton(self.frm_terms_and_conditions)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_agree.setFont(font)
        self.btn_agree.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_agree.setObjectName("btn_agree")
        self.lay_hor_buttons.addWidget(self.btn_agree)
        self.btn_dont_agree = QtWidgets.QPushButton(self.frm_terms_and_conditions)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_dont_agree.setFont(font)
        self.btn_dont_agree.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_dont_agree.setObjectName("btn_dont_agree")
        self.lay_hor_buttons.addWidget(self.btn_dont_agree)
        self.verticalLayout_3.addLayout(self.lay_hor_buttons)
        self.verticalLayout_2.addWidget(self.frm_terms_and_conditions)
        self.frm_footer = QtWidgets.QFrame(self.frm_principal)
        self.frm_footer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_footer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_footer.setObjectName("frm_footer")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frm_footer)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lbl_footer = QtWidgets.QLabel(self.frm_footer)
        self.lbl_footer.setObjectName("lbl_footer")
        self.horizontalLayout_2.addWidget(self.lbl_footer, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.verticalLayout_2.addWidget(self.frm_footer)
        self.horizontalLayout.addWidget(self.frm_principal)
        self.horizontalLayout.setStretch(0, 1)

        self.retranslateUi(Terms_and_conditions)
        QtCore.QMetaObject.connectSlotsByName(Terms_and_conditions)

    def retranslateUi(self, Terms_and_conditions):
        _translate = QtCore.QCoreApplication.translate
        Terms_and_conditions.setWindowTitle(_translate("Terms_and_conditions", "Terms and conditions"))
        self.lbl_terms_and_conditions.setText(_translate("Terms_and_conditions", "Terms and conditions"))
        self.txt_terms_and_conditions.setPlainText(_translate("Terms_and_conditions", "TERMS AND CONDITIONS\n"
"\n"
"            A.  SALE OR DISTRIBUTION WITHOUT AUTHORIZATION OF ALEJANDRO MEJIA IS PROHIBITED.\n"
"            B.  ALTERATION OF THE SOURCE CODE OR DESIGN OF THE GRAPHICAL INTERFACES IS PROHIBITED.\n"
"            C.  ALEJANDRO MEJIA IS NOT RESPONSIBLE FOR ANY MISUSE OF THIS SOFTWARE.\n"
"\n"
"          THE LEGAL AGREEMENTS SET FORTH BELOW GOVERN YOUR USE OF THIS SOFTWARE.\n"
"          (ALEJANDRO MEJIA), ARE NOT RESPONSIBLE FOR THE USE YOU MAKE OF THIS SOFTWARE AND ITS SERVICES.\n"
"          USE OF THIS SOFTWARE AND ITS SERVICES. TO AGREE TO THESE TERMS CLICK (I AGREE)\n"
"          IF YOU DO NOT AGREE TO THESE TERMS, CLICK (I DO NOT AGREE) AND DO NOT USE THIS SOFTWARE.\n"
"\n"
"          FOR MORE INFORMATION ABOUT OUR PRODUCTS OR SERVICES, PLEASE VISIT\n"
"          https://github.com/Alejandrox27"))
        self.btn_agree.setText(_translate("Terms_and_conditions", "I agree"))
        self.btn_dont_agree.setText(_translate("Terms_and_conditions", "I don\'t agree"))
        self.lbl_footer.setText(_translate("Terms_and_conditions", "Copyright - Alejandro Mejía - Nerfliz 2023"))
